import { useState } from "react";
import { Box, Divider, Stack, Text, Button } from "@chakra-ui/react";
import Head from "next/head";
import { ImPlus, ImHeart } from "react-icons/im";
import FullLogo from "components/Icons/FullLogo/FullLogo";
import Home from "components/Icons/Home/Home";
import Search from "components/Icons/Search/Search";
import Library from "components/Icons/Library/Library";
import Plus from "components/Icons/Plus/Plus";
import Heart from "components/Icons/Heart/Heart";

const menuSidebar = [
  { id: 1, text: "Home", Icon: Home },
  { id: 2, text: "Search", Icon: Search },
  { id: 3, text: "Your Library", Icon: Library },
];

export default function () {
  const [idItemMenuSelected, setIdItemMenuSelected] = useState(1);

  return (
    <>
      <Head>
        <title>Spotify clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        className="main"
        display="grid"
        gridTemplateAreas={{
          base: `"sidebar header" "sidebar content" "player player"`,
        }}
        width="100vw"
        maxWidth="1920px"
        height="100vh"
        gridTemplateRows="60px 1fr 90px"
        gridTemplateColumns="240px 1fr"
      >
        <Box gridArea="header" as="header" backgroundColor="blackAlpha.400">
          Header
        </Box>
        <Box gridArea="sidebar" as="aside" backgroundColor="blackAlpha.900">
          <Stack
            pl={5}
            direction="column"
            color="whiteAlpha.700"
            fontWeight={500}
          >
            <Stack pl={3} direction="row" alignItems="center" spacing={4}>
              <FullLogo color="#fff" width={120} height={80} />
            </Stack>

            {menuSidebar.map((itemMenu) => {
              const { id, text, Icon } = itemMenu;
              const itemSelected = idItemMenuSelected === id;
              const buttonColor = itemSelected ? "brand.800" : "inherit";
              const buttonTextColor = itemSelected ? "white" : "whiteAlpha.700";

              return (
                <Stack key={id} direction="row" alignItems="center" spacing={6}>
                  <Button
                    _hover={{ backgroundColor: { buttonColor } }}
                    backgroundColor={buttonColor}
                    color={buttonTextColor}
                    fontSize="14px"
                    justifyContent="start"
                    leftIcon={<Icon />}
                    variant="solid"
                    width="200px"
                  >
                    <Text pl={2}>{text}</Text>
                  </Button>
                </Stack>
              );
            })}

            <Stack pt={6} direction="row" alignItems="center" spacing={5}>
              <Button
                leftIcon={<Plus />}
                backgroundColor="inherit"
                _hover={{ backgroundColor: "inherit" }}
                variant="solid"
                width="200px"
                justifyContent="start"
                fontSize="14px"
              >
                <Text pl={2}>Create playlist</Text>
              </Button>
            </Stack>

            <Stack direction="row" alignItems="center" spacing={5}>
              <Button
                leftIcon={<Heart />}
                backgroundColor="inherit"
                _hover={{ backgroundColor: "inherit" }}
                variant="solid"
                width="200px"
                justifyContent="start"
                fontSize="14px"
              >
                <Text pl={2}>Liked songs</Text>
              </Button>
            </Stack>

            <Divider py={2} w="80%" borderColor="whiteAlpha.500" />
            <Box>
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((playlistId) => (
                <Text
                  color="whiteAlpha.700"
                  fontWeight={400}
                  py={1}
                  key={playlistId}
                >{`Playlist ${playlistId}`}</Text>
              ))}
            </Box>
          </Stack>
        </Box>
        <Box gridArea="content" as="section" backgroundColor="blackAlpha.500">
          <Text color="brand.500" fontWeight={600}>
            Content
          </Text>
        </Box>
        <Box gridArea="player" as="footer" backgroundColor="blackAlpha.400">
          Player
        </Box>
      </Box>
    </>
  );
}
